controller_list:
  - name: rarm_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
  - name: larm_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
  - name: rleg_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - RLEG_JOINT0
      - RLEG_JOINT1
      - RLEG_JOINT2
      - RLEG_JOINT3
      - RLEG_JOINT4
      - RLEG_JOINT5
      - RLEG_JOINT6
  - name: lleg_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - LLEG_JOINT0
      - LLEG_JOINT1
      - LLEG_JOINT2
      - LLEG_JOINT3
      - LLEG_JOINT4
      - LLEG_JOINT5
      - LLEG_JOINT6
  - name: torso_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
  - name: fullbody_without_head_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
      - RLEG_JOINT0
      - RLEG_JOINT1
      - RLEG_JOINT2
      - RLEG_JOINT3
      - RLEG_JOINT4
      - RLEG_JOINT5
      - RLEG_JOINT6
      - LLEG_JOINT0
      - LLEG_JOINT1
      - LLEG_JOINT2
      - LLEG_JOINT3
      - LLEG_JOINT4
      - LLEG_JOINT5
      - LLEG_JOINT6
      - CHEST_JOINT0
      - CHEST_JOINT1
      - virtual_joint
  - name: head_controller
    action_ns: follow_joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - HEAD_JOINT0
      - HEAD_JOINT1
